# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path('Resources/applicants_data.csv'))

# Review the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns = ['EIN', 'NAME'])

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == 'object'].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse_output=False)

In [7]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

# Display to confirm
encoded_data

array([[1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [8]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data, 
    columns = enc.get_feature_names_out(
        categorical_variables)
)
# Review the DataFrame
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [9]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([encoded_df, applicant_data_df.copy().drop(columns = categorical_variables)], axis = 1)

# Review the Dataframe
encoded_df # outbut is df after contatenation, includes number of rows and columns

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179,0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [10]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y # simply entering the name of target set shows its target, length, and data type

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [11]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns = "IS_SUCCESSFUL") # be sure to use a capital 'X'

# Review the features DataFrame
X # returns head and tail for review

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179

### Step 6: Split the features and target sets into training and testing datasets.

In [12]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [13]:
# Create a StandardScaler instance
scaler = StandardScaler() #  scales the features so that they have a mean of 0 and a standard deviation of 1; this helps model to converge more quickly, thus improving its performance

# Fit the scaler to the features training dataset
# `X-scaler` gets the mean and standard deviation of the training data and stores them in the `X-scaler` to ensure that the transformation will be based on the distribution of the training data.
# this will avoid information leakage from the test set
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train) # takes the data stored in `X_scaler` and uses to transform data by applying same transformation to test data
X_test_scaled = X_scaler.transform(X_test) # mean and standard deviation from the training data is now consistent with scaling of the test data

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [14]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0]) 

# Review the number of features
number_input_features # displays total length of `X` (should match the review of 'X' shown in Step 5

116

In [15]:
# Define the number of neurons in the output layer
number_output_neurons = 1 # the length of a single training example, so it is `1`

In [16]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  8

# Review the number hidden nodes in the first layer
hidden_nodes_layer1 # confirms 8 hidden nodes

8

In [17]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  4

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

4

In [18]:
# Create the Sequential model instance
nn = Sequential() # built-in class in Keras used for initializing a linear stack, ie. allows us to add layers in a sequentially

In [19]:
# Add the first hidden layer

# we use the activation function 'relu', the number of inputs was defined by our features
# `Dense` is a built-in class in Keras used to define a densely connected neural network layer
nn.add(
    Dense(
        units=hidden_nodes_layer1, 
        input_dim=number_input_features, 
        activation="relu"
    )
)

In [20]:
# Add the second hidden layer
nn.add(
    Dense(
        units=hidden_nodes_layer2, 
        activation="relu"
    )
)

In [21]:
# Add the output layer to the model specifying the number of output neurons and activation function
# we know `number_output_neurons` is one since it's a binary classification 
# `units` is a built-in parameter used to define the number of neurons
# `input-dim` is a built-in parameter that defines the input dimension
# `activation` is built-in parameter used to define the activation function
nn.add(Dense(units=number_output_neurons, activation="linear"))

In [22]:
# Display the Sequential model summary 
# ouput will show us the architecture
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 936

 dense_1 (Dense)             (None, 4)                 36

 dense_2 (Dense)             (None, 1)                 5

=================================================================
Total params: 977
Trainable params: 977
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [23]:
# Compile the Sequential model
nn.compile(
    loss="binary_crossentropy", # loss function for binary classification
    optimizer="adam", # ADAptive Moment estimation aka 'adam'
    metrics=["accuracy"]) # tracks accuracy during training

In [24]:
# Fit the model using 50 epochs and the training data
deep_net_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 782us/step - loss: 0.8421 - accuracy: 0.6911
Epoch 2/50
804/804 [==============================] - 1s 756us/step - loss: 0.7351 - accuracy: 0.7191
Epoch 3/50
804/804 [==============================] - 1s 763us/step - loss: 0.6488 - accuracy: 0.7118
Epoch 4/50
804/804 [==============================] - 1s 763us/step - loss: 0.6378 - accuracy: 0.7218
Epoch 5/50
804/804 [==============================] - 1s 795us/step - loss: 0.6294 - accuracy: 0.7195
Epoch 6/50
804/804 [==============================] - 1s 758us/step - loss: 0.6167 - accuracy: 0.7238
Epoch 7/50
804/804 [==============================] - 1s 766us/step - loss: 0.6282 - accuracy: 0.7279
Epoch 8/50
804/804 [==============================] - 1s 738us/step - loss: 0.6190 - accuracy: 0.7249
Epoch 9/50
804/804 [==============================] - 1s 777us/step - loss: 0.6144 - accuracy: 0.7261
Epoch 10/50
804/804 [==============================] - 1s 755us/step - loss: 0.6140 - accuracy: 0.7276
Epoch 11/50
804/804 [==============================] - 1s 745us/step - loss: 0.6093 - accuracy: 0.7276
Epoch 12/50
804/804 [==============================] - 1s 773us/step - loss: 0.6070 - accuracy: 0.7268
Epoch 13/50
804/804 [==============================] - 1s 753us/step - loss: 0.6018 - accuracy: 0.7285
Epoch 14/50
804/804 [==============================] - 1s 745us/step - loss: 0.6079 - accuracy: 0.7294
Epoch 15/50
804/804 [==============================] - 1s 777us/step - loss: 0.5992 - accuracy: 0.7271
Epoch 16/50
804/804 [==============================] - 1s 760us/step - loss: 0.5957 - accuracy: 0.7304
Epoch 17/50
804/804 [==============================] - 1s 778us/step - loss: 0.5961 - accuracy: 0.7283
Epoch 18/50
804/804 [==============================] - 1s 768us/step - loss: 0.5996 - accuracy: 0.7299
Epoch 19/50
804/804 [==============================] - 1s 786us/step - loss: 0.6017 - accuracy: 0.7294
Epoch 20/50
804/804 [==============================] - 1s 767us/step - loss: 0.6012 - accuracy: 0.7302
Epoch 21/50
804/804 [==============================] - 1s 839us/step - loss: 0.5981 - accuracy: 0.7306
Epoch 22/50
804/804 [==============================] - 1s 931us/step - loss: 0.5991 - accuracy: 0.7294
Epoch 23/50
804/804 [==============================] - 1s 936us/step - loss: 0.5927 - accuracy: 0.7309
Epoch 24/50
804/804 [==============================] - 1s 916us/step - loss: 0.5900 - accuracy: 0.7292
Epoch 25/50
804/804 [==============================] - 1s 931us/step - loss: 0.5893 - accuracy: 0.7320
Epoch 26/50
804/804 [==============================] - 1s 869us/step - loss: 0.5940 - accuracy: 0.7298
Epoch 27/50
804/804 [==============================] - 1s 898us/step - loss: 0.5967 - accuracy: 0.7312
Epoch 28/50
804/804 [==============================] - 1s 999us/step - loss: 0.5893 - accuracy: 0.7322
Epoch 29/50
804/804 [==============================] - 1s 887us/step - loss: 0.5869 - accuracy: 0.7308
Epoch 30/50
804/804 [==============================] - 1s 883us/step - loss: 0.5839 - accuracy: 0.7315
Epoch 31/50
804/804 [==============================] - 1s 891us/step - loss: 0.5909 - accuracy: 0.7305
Epoch 32/50
804/804 [==============================] - 1s 885us/step - loss: 0.5890 - accuracy: 0.7293
Epoch 33/50
804/804 [==============================] - 1s 869us/step - loss: 0.5842 - accuracy: 0.7315
Epoch 34/50
804/804 [==============================] - 1s 855us/step - loss: 0.5832 - accuracy: 0.7317
Epoch 35/50
804/804 [==============================] - 1s 839us/step - loss: 0.5847 - accuracy: 0.7299
Epoch 36/50
804/804 [==============================] - 1s 955us/step - loss: 0.5813 - accuracy: 0.7293
Epoch 37/50
804/804 [==============================] - 1s 920us/step - loss: 0.5822 - accuracy: 0.7310
Epoch 38/50
804/804 [==============================] - 1s 926us/step - loss: 0.5756 - accuracy: 0.7324
Epoch 39/50
804/804 [==============================] - 1s 942us/step - loss: 0.5737 - accuracy: 0.7334
Epoch 40/50
804/804 [==============================] - 1s 1000us/step - loss: 0.5747 - accuracy: 0.7342
Epoch 41/50
804/804 [==============================] - 1s 978us/step - loss: 0.5752 - accuracy: 0.7322
Epoch 42/50
804/804 [==============================] - 1s 969us/step - loss: 0.5745 - accuracy: 0.7326
Epoch 43/50
804/804 [==============================] - 1s 890us/step - loss: 0.5800 - accuracy: 0.7314
Epoch 44/50
804/804 [==============================] - 1s 869us/step - loss: 0.5744 - accuracy: 0.7327
Epoch 45/50
804/804 [==============================] - 1s 909us/step - loss: 0.5754 - accuracy: 0.7314
Epoch 46/50
804/804 [==============================] - 1s 874us/step - loss: 0.5732 - accuracy: 0.7332
Epoch 47/50
804/804 [==============================] - 1s 899us/step - loss: 0.5721 - accuracy: 0.7323
Epoch 48/50
804/804 [==============================] - 1s 882us/step - loss: 0.5727 - accuracy: 0.7316
Epoch 49/50
804/804 [==============================] - 1s 871us/step - loss: 0.5726 - accuracy: 0.7325
Epoch 50/50
804/804 [==============================] - 1s 889us/step - loss: 0.5725 - accuracy: 0.7313

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [25]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, # input data for the test set, already scaled
                                         y_test, # actual outputs aka 'ground truth'
                                         verbose = 2 # value of 2 means method will output detailed info re: evaluation process
                                        )

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5857 - accuracy: 0.7255 - 272ms/epoch - 1ms/step
Loss: 0.5856576561927795, Accuracy: 0.7254810333251953

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [26]:
# Set the model's file path
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path) # saves our model in 'Resources' folder

In [27]:
import h5py

def print_structure(file_path):
    with h5py.File(file_path, 'r') as file:
        file.visititems(lambda name, obj: print(name, obj))

file_path = "Resources/AlphabetSoup.h5"
print_structure(file_path)

model_weights <HDF5 group "/model_weights" (4 members)>
model_weights/dense <HDF5 group "/model_weights/dense" (1 members)>
model_weights/dense/dense <HDF5 group "/model_weights/dense/dense" (2 members)>
model_weights/dense/dense/bias:0 <HDF5 dataset "bias:0": shape (8,), type "<f4">
model_weights/dense/dense/kernel:0 <HDF5 dataset "kernel:0": shape (116, 8), type "<f4">
model_weights/dense_1 <HDF5 group "/model_weights/dense_1" (1 members)>
model_weights/dense_1/dense_1 <HDF5 group "/model_weights/dense_1/dense_1" (2 members)>
model_weights/dense_1/dense_1/bias:0 <HDF5 dataset "bias:0": shape (4,), type "<f4">
model_weights/dense_1/dense_1/kernel:0 <HDF5 dataset "kernel:0": shape (8, 4), type "<f4">
model_weights/dense_2 <HDF5 group "/model_weights/dense_2" (1 members)>
model_weights/dense_2/dense_2 <HDF5 group "/model_weights/dense_2/dense_2" (2 members)>
model_weights/dense_2/dense_2/bias:0 <HDF5 dataset "bias:0": shape (1,), type "<f4">
model_weights/dense_2/dense_2/kernel:0 <HDF5 dataset "kernel:0": shape (4, 1), type "<f4">
model_weights/top_level_model_weights <HDF5 group "/model_weights/top_level_model_weights" (0 members)>
optimizer_weights <HDF5 group "/optimizer_weights" (1 members)>
optimizer_weights/Adam <HDF5 group "/optimizer_weights/Adam" (4 members)>
optimizer_weights/Adam/dense <HDF5 group "/optimizer_weights/Adam/dense" (2 members)>
optimizer_weights/Adam/dense/bias <HDF5 group "/optimizer_weights/Adam/dense/bias" (2 members)>
optimizer_weights/Adam/dense/bias/m:0 <HDF5 dataset "m:0": shape (8,), type "<f4">
optimizer_weights/Adam/dense/bias/v:0 <HDF5 dataset "v:0": shape (8,), type "<f4">
optimizer_weights/Adam/dense/kernel <HDF5 group "/optimizer_weights/Adam/dense/kernel" (2 members)>
optimizer_weights/Adam/dense/kernel/m:0 <HDF5 dataset "m:0": shape (116, 8), type "<f4">
optimizer_weights/Adam/dense/kernel/v:0 <HDF5 dataset "v:0": shape (116, 8), type "<f4">
optimizer_weights/Adam/dense_1 <HDF5 group "/optimizer_weights/Adam/dense_1" (2 members)>
optimizer_weights/Adam/dense_1/bias <HDF5 group "/optimizer_weights/Adam/dense_1/bias" (2 members)>
optimizer_weights/Adam/dense_1/bias/m:0 <HDF5 dataset "m:0": shape (4,), type "<f4">
optimizer_weights/Adam/dense_1/bias/v:0 <HDF5 dataset "v:0": shape (4,), type "<f4">
optimizer_weights/Adam/dense_1/kernel <HDF5 group "/optimizer_weights/Adam/dense_1/kernel" (2 members)>
optimizer_weights/Adam/dense_1/kernel/m:0 <HDF5 dataset "m:0": shape (8, 4), type "<f4">
optimizer_weights/Adam/dense_1/kernel/v:0 <HDF5 dataset "v:0": shape (8, 4), type "<f4">
optimizer_weights/Adam/dense_2 <HDF5 group "/optimizer_weights/Adam/dense_2" (2 members)>
optimizer_weights/Adam/dense_2/bias <HDF5 group "/optimizer_weights/Adam/dense_2/bias" (2 members)>
optimizer_weights/Adam/dense_2/bias/m:0 <HDF5 dataset "m:0": shape (1,), type "<f4">
optimizer_weights/Adam/dense_2/bias/v:0 <HDF5 dataset "v:0": shape (1,), type "<f4">
optimizer_weights/Adam/dense_2/kernel <HDF5 group "/optimizer_weights/Adam/dense_2/kernel" (2 members)>
optimizer_weights/Adam/dense_2/kernel/m:0 <HDF5 dataset "m:0": shape (4, 1), type "<f4">
optimizer_weights/Adam/dense_2/kernel/v:0 <HDF5 dataset "v:0": shape (4, 1), type "<f4">
optimizer_weights/Adam/iter:0 <HDF5 dataset "iter:0": shape (), type "<i8">

In [28]:
from tensorflow.keras.models import load_model

model = load_model("Resources/AlphabetSoup.h5")
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 936

 dense_1 (Dense)             (None, 4)                 36

 dense_2 (Dense)             (None, 1)                 5

=================================================================
Total params: 977
Trainable params: 977
Non-trainable params: 0
_________________________________________________________________

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [29]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [30]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 2

In [31]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = round((len(X_train.iloc[0]) + number_output_neurons_A1))

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

118

In [32]:
# Create the Sequential model instance 
nn_A1 = Sequential()

In [33]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1, activation="linear"))

# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 118)               13806

 dense_4 (Dense)             (None, 2)                 238

=================================================================
Total params: 14,044
Trainable params: 14,044
Non-trainable params: 0
_________________________________________________________________

In [34]:
# Compile the Sequential model
nn_A1.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [35]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(
    X_train_scaled,
    y_train, 
    epochs=100 #changed epochs to 100
)

Epoch 1/100
804/804 [==============================] - 1s 962us/step - loss: 1.4552 - accuracy: 0.4743
Epoch 2/100
804/804 [==============================] - 1s 937us/step - loss: 1.6635 - accuracy: 0.4596
Epoch 3/100
804/804 [==============================] - 1s 992us/step - loss: 1.5208 - accuracy: 0.4663
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 1.7363 - accuracy: 0.5142
Epoch 5/100
804/804 [==============================] - 1s 953us/step - loss: 1.6844 - accuracy: 0.4979
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 1.7825 - accuracy: 0.5519
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 1.8260 - accuracy: 0.5146
Epoch 8/100
804/804 [==============================] - 1s 953us/step - loss: 1.7179 - accuracy: 0.4925
Epoch 9/100
804/804 [==============================] - 1s 967us/step - loss: 1.6079 - accuracy: 0.5054
Epoch 10/100
804/804 [==============================] - 1s 974us/step - loss: 1.9592 - accuracy: 0.5217
Epoch 11/100
804/804 [==============================] - 1s 995us/step - loss: 1.9401 - accuracy: 0.4828
Epoch 12/100
804/804 [==============================] - 1s 987us/step - loss: 1.6459 - accuracy: 0.5221
Epoch 13/100
804/804 [==============================] - 1s 991us/step - loss: 1.4223 - accuracy: 0.5567
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 1.2962 - accuracy: 0.5398
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 1.1238 - accuracy: 0.5461
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 1.0891 - accuracy: 0.5231
Epoch 17/100
804/804 [==============================] - 1s 996us/step - loss: 1.4083 - accuracy: 0.5654
Epoch 18/100
804/804 [==============================] - 1s 978us/step - loss: 1.3560 - accuracy: 0.5501
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 1.3082 - accuracy: 0.5314
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 1.2897 - accuracy: 0.4687
Epoch 21/100
804/804 [==============================] - 1s 959us/step - loss: 1.3795 - accuracy: 0.4539
Epoch 22/100
804/804 [==============================] - 1s 992us/step - loss: 1.3022 - accuracy: 0.4854
Epoch 23/100
804/804 [==============================] - 1s 940us/step - loss: 1.2864 - accuracy: 0.5028
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 1.4047 - accuracy: 0.5341
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 1.6323 - accuracy: 0.5197
Epoch 26/100
804/804 [==============================] - 1s 952us/step - loss: 1.5257 - accuracy: 0.5292
Epoch 27/100
804/804 [==============================] - 1s 952us/step - loss: 1.3615 - accuracy: 0.5211
Epoch 28/100
804/804 [==============================] - 1s 932us/step - loss: 1.3725 - accuracy: 0.5024
Epoch 29/100
804/804 [==============================] - 1s 971us/step - loss: 1.4047 - accuracy: 0.5218
Epoch 30/100
804/804 [==============================] - 1s 994us/step - loss: 1.3847 - accuracy: 0.5097
Epoch 31/100
804/804 [==============================] - 1s 974us/step - loss: 1.1037 - accuracy: 0.5318
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 1.1589 - accuracy: 0.5131
Epoch 33/100
804/804 [==============================] - 1s 932us/step - loss: 1.1616 - accuracy: 0.5051
Epoch 34/100
804/804 [==============================] - 1s 993us/step - loss: 1.1099 - accuracy: 0.5133
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 1.4479 - accuracy: 0.5176
Epoch 36/100
804/804 [==============================] - 1s 981us/step - loss: 1.4766 - accuracy: 0.5537
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 1.0559 - accuracy: 0.5872
Epoch 38/100
804/804 [==============================] - 1s 974us/step - loss: 1.0390 - accuracy: 0.5622
Epoch 39/100
804/804 [==============================] - 1s 932us/step - loss: 1.0989 - accuracy: 0.5692
Epoch 40/100
804/804 [==============================] - 1s 978us/step - loss: 1.0896 - accuracy: 0.5481
Epoch 41/100
804/804 [==============================] - 1s 973us/step - loss: 1.0814 - accuracy: 0.5016
Epoch 42/100
804/804 [==============================] - 1s 995us/step - loss: 1.2084 - accuracy: 0.5186
Epoch 43/100
804/804 [==============================] - 1s 986us/step - loss: 1.1486 - accuracy: 0.5207
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 1.0929 - accuracy: 0.4993
Epoch 45/100
804/804 [==============================] - 1s 999us/step - loss: 1.0813 - accuracy: 0.5220
Epoch 46/100
804/804 [==============================] - 1s 974us/step - loss: 1.0422 - accuracy: 0.5295
Epoch 47/100
804/804 [==============================] - 1s 992us/step - loss: 1.0956 - accuracy: 0.5031
Epoch 48/100
804/804 [==============================] - 1s 948us/step - loss: 1.0484 - accuracy: 0.5024
Epoch 49/100
804/804 [==============================] - 1s 950us/step - loss: 1.1116 - accuracy: 0.5271
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 1.0453 - accuracy: 0.5015
Epoch 51/100
804/804 [==============================] - 1s 956us/step - loss: 1.1631 - accuracy: 0.5238
Epoch 52/100
804/804 [==============================] - 1s 980us/step - loss: 1.1054 - accuracy: 0.4805
Epoch 53/100
804/804 [==============================] - 1s 994us/step - loss: 1.0109 - accuracy: 0.5017
Epoch 54/100
804/804 [==============================] - 1s 937us/step - loss: 1.0046 - accuracy: 0.4803
Epoch 55/100
804/804 [==============================] - 1s 974us/step - loss: 1.0029 - accuracy: 0.4927
Epoch 56/100
804/804 [==============================] - 1s 989us/step - loss: 1.0303 - accuracy: 0.5011
Epoch 57/100
804/804 [==============================] - 1s 928us/step - loss: 1.0057 - accuracy: 0.5238
Epoch 58/100
804/804 [==============================] - 1s 932us/step - loss: 1.1152 - accuracy: 0.5219
Epoch 59/100
804/804 [==============================] - 1s 979us/step - loss: 1.0817 - accuracy: 0.5198
Epoch 60/100
804/804 [==============================] - 1s 962us/step - loss: 1.0993 - accuracy: 0.5272
Epoch 61/100
804/804 [==============================] - 1s 952us/step - loss: 1.1534 - accuracy: 0.4977
Epoch 62/100
804/804 [==============================] - 1s 991us/step - loss: 1.0216 - accuracy: 0.4902
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.9711 - accuracy: 0.4827
Epoch 64/100
804/804 [==============================] - 1s 947us/step - loss: 0.9802 - accuracy: 0.5284
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.9402 - accuracy: 0.5515
Epoch 66/100
804/804 [==============================] - 1s 930us/step - loss: 0.8299 - accuracy: 0.5176
Epoch 67/100
804/804 [==============================] - 1s 956us/step - loss: 0.8225 - accuracy: 0.4730
Epoch 68/100
804/804 [==============================] - 1s 969us/step - loss: 0.8736 - accuracy: 0.5114
Epoch 69/100
804/804 [==============================] - 1s 957us/step - loss: 0.8287 - accuracy: 0.5023
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.8320 - accuracy: 0.5056
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.8638 - accuracy: 0.5154
Epoch 72/100
804/804 [==============================] - 1s 939us/step - loss: 0.9500 - accuracy: 0.5230
Epoch 73/100
804/804 [==============================] - 1s 953us/step - loss: 1.0502 - accuracy: 0.4990
Epoch 74/100
804/804 [==============================] - 1s 994us/step - loss: 1.2931 - accuracy: 0.4673
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 1.2480 - accuracy: 0.5061
Epoch 76/100
804/804 [==============================] - 1s 935us/step - loss: 1.1038 - accuracy: 0.4738
Epoch 77/100
804/804 [==============================] - 1s 970us/step - loss: 1.0184 - accuracy: 0.4857
Epoch 78/100
804/804 [==============================] - 1s 987us/step - loss: 1.0033 - accuracy: 0.4910
Epoch 79/100
804/804 [==============================] - 1s 997us/step - loss: 0.9897 - accuracy: 0.5003
Epoch 80/100
804/804 [==============================] - 1s 965us/step - loss: 1.2157 - accuracy: 0.5103
Epoch 81/100
804/804 [==============================] - 1s 975us/step - loss: 1.1930 - accuracy: 0.5162
Epoch 82/100
804/804 [==============================] - 1s 933us/step - loss: 1.2323 - accuracy: 0.4892
Epoch 83/100
804/804 [==============================] - 1s 946us/step - loss: 1.2465 - accuracy: 0.5006
Epoch 84/100
804/804 [==============================] - 1s 932us/step - loss: 1.2206 - accuracy: 0.4937
Epoch 85/100
804/804 [==============================] - 1s 974us/step - loss: 1.1518 - accuracy: 0.4754
Epoch 86/100
804/804 [==============================] - 1s 951us/step - loss: 1.1183 - accuracy: 0.4955
Epoch 87/100
804/804 [==============================] - 1s 962us/step - loss: 1.0090 - accuracy: 0.4984
Epoch 88/100
804/804 [==============================] - 1s 978us/step - loss: 1.0155 - accuracy: 0.4956
Epoch 89/100
804/804 [==============================] - 1s 927us/step - loss: 0.9679 - accuracy: 0.4910
Epoch 90/100
804/804 [==============================] - 1s 927us/step - loss: 0.9595 - accuracy: 0.4705
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.8975 - accuracy: 0.4388
Epoch 92/100
804/804 [==============================] - 1s 928us/step - loss: 0.8772 - accuracy: 0.4885
Epoch 93/100
804/804 [==============================] - 1s 939us/step - loss: 0.9055 - accuracy: 0.3891
Epoch 94/100
804/804 [==============================] - 1s 939us/step - loss: 0.8380 - accuracy: 0.4537
Epoch 95/100
804/804 [==============================] - 1s 944us/step - loss: 0.8031 - accuracy: 0.4791
Epoch 96/100
804/804 [==============================] - 1s 960us/step - loss: 0.8340 - accuracy: 0.4182
Epoch 97/100
804/804 [==============================] - 1s 954us/step - loss: 0.8093 - accuracy: 0.4580
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.8720 - accuracy: 0.5035
Epoch 99/100
804/804 [==============================] - 1s 999us/step - loss: 0.8111 - accuracy: 0.4925
Epoch 100/100
804/804 [==============================] - 1s 965us/step - loss: 0.7455 - accuracy: 0.4408

#### Alternative Model 2

In [36]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [37]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [38]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = round(
    len(X_train.iloc[0]) * 1/2 + number_output_neurons_A2
)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

59

In [39]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [40]:
# First hidden layer
nn_A2.add(
    Dense(
        units=hidden_nodes_layer1_A2, 
        input_dim=number_input_features,
        activation="relu")
)

# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2, activation="linear"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 59)                6903

 dense_6 (Dense)             (None, 1)                 60

=================================================================
Total params: 6,963
Trainable params: 6,963
Non-trainable params: 0
_________________________________________________________________

In [41]:
# Compile the model
nn_A2.compile(
    loss="binary_crossentropy", 
    optimizer="adam", 
    metrics=["accuracy"]
)

In [42]:
# Fit the model
fit_model_A2 = nn_A2.fit(
    X_train_scaled, 
    y_train, 
    epochs=100 # changed epoch to 100
)

Epoch 1/100
804/804 [==============================] - 1s 860us/step - loss: 1.4268 - accuracy: 0.6765
Epoch 2/100
804/804 [==============================] - 1s 868us/step - loss: 1.2752 - accuracy: 0.6918
Epoch 3/100
804/804 [==============================] - 1s 892us/step - loss: 1.3867 - accuracy: 0.6890
Epoch 4/100
804/804 [==============================] - 1s 849us/step - loss: 1.9041 - accuracy: 0.6750
Epoch 5/100
804/804 [==============================] - 1s 867us/step - loss: 1.9375 - accuracy: 0.6742
Epoch 6/100
804/804 [==============================] - 1s 901us/step - loss: 2.0047 - accuracy: 0.6666
Epoch 7/100
804/804 [==============================] - 1s 877us/step - loss: 1.7108 - accuracy: 0.6756
Epoch 8/100
804/804 [==============================] - 1s 904us/step - loss: 1.2428 - accuracy: 0.6985
Epoch 9/100
804/804 [==============================] - 1s 966us/step - loss: 1.2168 - accuracy: 0.7001
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 1.5264 - accuracy: 0.6858
Epoch 11/100
804/804 [==============================] - 1s 904us/step - loss: 1.1968 - accuracy: 0.7013
Epoch 12/100
804/804 [==============================] - 1s 895us/step - loss: 1.1502 - accuracy: 0.7071
Epoch 13/100
804/804 [==============================] - 1s 952us/step - loss: 1.3082 - accuracy: 0.7047
Epoch 14/100
804/804 [==============================] - 1s 867us/step - loss: 1.2191 - accuracy: 0.7056
Epoch 15/100
804/804 [==============================] - 1s 884us/step - loss: 1.1252 - accuracy: 0.7053
Epoch 16/100
804/804 [==============================] - 1s 992us/step - loss: 1.1397 - accuracy: 0.6988
Epoch 17/100
804/804 [==============================] - 1s 978us/step - loss: 0.8978 - accuracy: 0.7170
Epoch 18/100
804/804 [==============================] - 1s 940us/step - loss: 1.0601 - accuracy: 0.6819
Epoch 19/100
804/804 [==============================] - 1s 977us/step - loss: 0.9878 - accuracy: 0.7181
Epoch 20/100
804/804 [==============================] - 1s 963us/step - loss: 0.9681 - accuracy: 0.7196
Epoch 21/100
804/804 [==============================] - 1s 942us/step - loss: 0.9609 - accuracy: 0.7221
Epoch 22/100
804/804 [==============================] - 1s 930us/step - loss: 1.0267 - accuracy: 0.7145
Epoch 23/100
804/804 [==============================] - 1s 945us/step - loss: 0.9974 - accuracy: 0.7072
Epoch 24/100
804/804 [==============================] - 1s 879us/step - loss: 0.9524 - accuracy: 0.7195
Epoch 25/100
804/804 [==============================] - 1s 869us/step - loss: 0.9505 - accuracy: 0.7195
Epoch 26/100
804/804 [==============================] - 1s 887us/step - loss: 0.8490 - accuracy: 0.7151
Epoch 27/100
804/804 [==============================] - 1s 923us/step - loss: 0.8425 - accuracy: 0.7189
Epoch 28/100
804/804 [==============================] - 1s 877us/step - loss: 0.8276 - accuracy: 0.7270
Epoch 29/100
804/804 [==============================] - 1s 909us/step - loss: 0.8275 - accuracy: 0.7191
Epoch 30/100
804/804 [==============================] - 1s 923us/step - loss: 0.8185 - accuracy: 0.7268
Epoch 31/100
804/804 [==============================] - 1s 914us/step - loss: 0.8120 - accuracy: 0.7282
Epoch 32/100
804/804 [==============================] - 1s 995us/step - loss: 0.8070 - accuracy: 0.7285
Epoch 33/100
804/804 [==============================] - 1s 899us/step - loss: 0.8219 - accuracy: 0.7270
Epoch 34/100
804/804 [==============================] - 1s 931us/step - loss: 0.8128 - accuracy: 0.7268
Epoch 35/100
804/804 [==============================] - 1s 910us/step - loss: 0.8114 - accuracy: 0.7217
Epoch 36/100
804/804 [==============================] - 1s 880us/step - loss: 0.7884 - accuracy: 0.7276
Epoch 37/100
804/804 [==============================] - 1s 934us/step - loss: 0.8550 - accuracy: 0.7172
Epoch 38/100
804/804 [==============================] - 1s 941us/step - loss: 0.8250 - accuracy: 0.7139
Epoch 39/100
804/804 [==============================] - 1s 881us/step - loss: 0.8729 - accuracy: 0.7122
Epoch 40/100
804/804 [==============================] - 1s 861us/step - loss: 0.8067 - accuracy: 0.7236
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.7602 - accuracy: 0.7277
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.7511 - accuracy: 0.7261
Epoch 43/100
804/804 [==============================] - 1s 930us/step - loss: 0.8087 - accuracy: 0.7151
Epoch 44/100
804/804 [==============================] - 1s 922us/step - loss: 0.8030 - accuracy: 0.7252
Epoch 45/100
804/804 [==============================] - 1s 884us/step - loss: 0.7016 - accuracy: 0.7313
Epoch 46/100
804/804 [==============================] - 1s 890us/step - loss: 0.6866 - accuracy: 0.7325
Epoch 47/100
804/804 [==============================] - 1s 931us/step - loss: 0.6881 - accuracy: 0.7304
Epoch 48/100
804/804 [==============================] - 1s 971us/step - loss: 0.6997 - accuracy: 0.7281
Epoch 49/100
804/804 [==============================] - 1s 916us/step - loss: 0.7133 - accuracy: 0.7291
Epoch 50/100
804/804 [==============================] - 1s 910us/step - loss: 0.7161 - accuracy: 0.7243
Epoch 51/100
804/804 [==============================] - 1s 944us/step - loss: 0.7015 - accuracy: 0.7295
Epoch 52/100
804/804 [==============================] - 1s 990us/step - loss: 0.6850 - accuracy: 0.7319
Epoch 53/100
804/804 [==============================] - 1s 902us/step - loss: 0.6838 - accuracy: 0.7297
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.7535 - accuracy: 0.7218
Epoch 55/100
804/804 [==============================] - 1s 917us/step - loss: 0.6962 - accuracy: 0.7290
Epoch 56/100
804/804 [==============================] - 1s 896us/step - loss: 0.6916 - accuracy: 0.7329
Epoch 57/100
804/804 [==============================] - 1s 971us/step - loss: 0.6872 - accuracy: 0.7329
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.7452 - accuracy: 0.7096
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.7048 - accuracy: 0.7304
Epoch 60/100
804/804 [==============================] - 1s 973us/step - loss: 0.6892 - accuracy: 0.7321
Epoch 61/100
804/804 [==============================] - 1s 911us/step - loss: 0.6802 - accuracy: 0.7313
Epoch 62/100
804/804 [==============================] - 1s 912us/step - loss: 0.6849 - accuracy: 0.7313
Epoch 63/100
804/804 [==============================] - 1s 864us/step - loss: 0.6861 - accuracy: 0.7317
Epoch 64/100
804/804 [==============================] - 1s 945us/step - loss: 0.6813 - accuracy: 0.7330
Epoch 65/100
804/804 [==============================] - 1s 880us/step - loss: 0.6894 - accuracy: 0.7307
Epoch 66/100
804/804 [==============================] - 1s 893us/step - loss: 0.6831 - accuracy: 0.7338
Epoch 67/100
804/804 [==============================] - 1s 924us/step - loss: 0.7843 - accuracy: 0.7265
Epoch 68/100
804/804 [==============================] - 1s 914us/step - loss: 0.7086 - accuracy: 0.7309
Epoch 69/100
804/804 [==============================] - 1s 978us/step - loss: 0.6922 - accuracy: 0.7324
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6955 - accuracy: 0.7300
Epoch 71/100
804/804 [==============================] - 1s 890us/step - loss: 0.6894 - accuracy: 0.7310
Epoch 72/100
804/804 [==============================] - 1s 957us/step - loss: 0.7021 - accuracy: 0.7275
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6869 - accuracy: 0.7305
Epoch 74/100
804/804 [==============================] - 1s 969us/step - loss: 0.6939 - accuracy: 0.7293
Epoch 75/100
804/804 [==============================] - 1s 888us/step - loss: 0.7225 - accuracy: 0.7294
Epoch 76/100
804/804 [==============================] - 1s 894us/step - loss: 0.6935 - accuracy: 0.7296
Epoch 77/100
804/804 [==============================] - 1s 888us/step - loss: 0.7025 - accuracy: 0.7236
Epoch 78/100
804/804 [==============================] - 1s 988us/step - loss: 0.6871 - accuracy: 0.7292
Epoch 79/100
804/804 [==============================] - 1s 874us/step - loss: 0.7660 - accuracy: 0.7200
Epoch 80/100
804/804 [==============================] - 1s 903us/step - loss: 0.6845 - accuracy: 0.7303
Epoch 81/100
804/804 [==============================] - 1s 907us/step - loss: 0.6850 - accuracy: 0.7329
Epoch 82/100
804/804 [==============================] - 1s 892us/step - loss: 0.6994 - accuracy: 0.7312
Epoch 83/100
804/804 [==============================] - 1s 858us/step - loss: 0.6918 - accuracy: 0.7301
Epoch 84/100
804/804 [==============================] - 1s 911us/step - loss: 0.6919 - accuracy: 0.7290
Epoch 85/100
804/804 [==============================] - 1s 889us/step - loss: 0.6828 - accuracy: 0.7327
Epoch 86/100
804/804 [==============================] - 1s 906us/step - loss: 0.6775 - accuracy: 0.7330
Epoch 87/100
804/804 [==============================] - 1s 876us/step - loss: 0.7977 - accuracy: 0.7215
Epoch 88/100
804/804 [==============================] - 1s 875us/step - loss: 0.9983 - accuracy: 0.7128
Epoch 89/100
804/804 [==============================] - 1s 874us/step - loss: 1.0230 - accuracy: 0.7057
Epoch 90/100
804/804 [==============================] - 1s 901us/step - loss: 0.8595 - accuracy: 0.7194
Epoch 91/100
804/804 [==============================] - 1s 916us/step - loss: 0.7125 - accuracy: 0.7273
Epoch 92/100
804/804 [==============================] - 1s 881us/step - loss: 0.7032 - accuracy: 0.7267
Epoch 93/100
804/804 [==============================] - 1s 890us/step - loss: 0.7313 - accuracy: 0.7274
Epoch 94/100
804/804 [==============================] - 1s 888us/step - loss: 0.6987 - accuracy: 0.7297
Epoch 95/100
804/804 [==============================] - 1s 958us/step - loss: 0.6919 - accuracy: 0.7274
Epoch 96/100
804/804 [==============================] - 1s 906us/step - loss: 0.6844 - accuracy: 0.7317
Epoch 97/100
804/804 [==============================] - 1s 916us/step - loss: 0.6849 - accuracy: 0.7301
Epoch 98/100
804/804 [==============================] - 1s 914us/step - loss: 0.7730 - accuracy: 0.7172
Epoch 99/100
804/804 [==============================] - 1s 994us/step - loss: 0.7037 - accuracy: 0.7306
Epoch 100/100
804/804 [==============================] - 1s 922us/step - loss: 0.7018 - accuracy: 0.7317

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [43]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, 
                                         y_test, 
                                         verbose = 2 # prints 1 line of info for each eval step
                                        )

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5857 - accuracy: 0.7255 - 180ms/epoch - 673us/step
Loss: 0.5856576561927795, Accuracy: 0.7254810333251953

In [44]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(
    X_test_scaled, 
    y_test, 
    verbose = 2
)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.7375 - accuracy: 0.4210 - 250ms/epoch - 934us/step
Loss: 0.7375186085700989, Accuracy: 0.4209912419319153

In [45]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(
    X_test_scaled,
    y_test, 
    verbose = 2
)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.6943 - accuracy: 0.7262 - 243ms/epoch - 906us/step
Loss: 0.6942727565765381, Accuracy: 0.7261807322502136

### Step 3: Save each of your alternative models as an HDF5 file.

In [46]:
# Set the file path for the first alternative model
file_path = Path("Resources/AlphabetSoup_alt_1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [47]:
# Set the file path for the second alternative model
file_path = Path("Resources/AlphabetSoup_alt_2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)



## Check out the H5PY or input your own model with 'Keras':

In [48]:

# 1) Print the names and objects of everything inside the HDF5 file

import h5py

def print_structure(file_path):
    with h5py.File(file_path, 'r') as file:
        file.visititems(lambda name, obj: print(name, obj))

file_path = "Resources/AlphabetSoup.h5"
print_structure(file_path)

model_weights <HDF5 group "/model_weights" (4 members)>
model_weights/dense <HDF5 group "/model_weights/dense" (1 members)>
model_weights/dense/dense <HDF5 group "/model_weights/dense/dense" (2 members)>
model_weights/dense/dense/bias:0 <HDF5 dataset "bias:0": shape (8,), type "<f4">
model_weights/dense/dense/kernel:0 <HDF5 dataset "kernel:0": shape (116, 8), type "<f4">
model_weights/dense_1 <HDF5 group "/model_weights/dense_1" (1 members)>
model_weights/dense_1/dense_1 <HDF5 group "/model_weights/dense_1/dense_1" (2 members)>
model_weights/dense_1/dense_1/bias:0 <HDF5 dataset "bias:0": shape (4,), type "<f4">
model_weights/dense_1/dense_1/kernel:0 <HDF5 dataset "kernel:0": shape (8, 4), type "<f4">
model_weights/dense_2 <HDF5 group "/model_weights/dense_2" (1 members)>
model_weights/dense_2/dense_2 <HDF5 group "/model_weights/dense_2/dense_2" (2 members)>
model_weights/dense_2/dense_2/bias:0 <HDF5 dataset "bias:0": shape (1,), type "<f4">
model_weights/dense_2/dense_2/kernel:0 <HDF5 dataset "kernel:0": shape (4, 1), type "<f4">
model_weights/top_level_model_weights <HDF5 group "/model_weights/top_level_model_weights" (0 members)>
optimizer_weights <HDF5 group "/optimizer_weights" (1 members)>
optimizer_weights/Adam <HDF5 group "/optimizer_weights/Adam" (4 members)>
optimizer_weights/Adam/dense <HDF5 group "/optimizer_weights/Adam/dense" (2 members)>
optimizer_weights/Adam/dense/bias <HDF5 group "/optimizer_weights/Adam/dense/bias" (2 members)>
optimizer_weights/Adam/dense/bias/m:0 <HDF5 dataset "m:0": shape (8,), type "<f4">
optimizer_weights/Adam/dense/bias/v:0 <HDF5 dataset "v:0": shape (8,), type "<f4">
optimizer_weights/Adam/dense/kernel <HDF5 group "/optimizer_weights/Adam/dense/kernel" (2 members)>
optimizer_weights/Adam/dense/kernel/m:0 <HDF5 dataset "m:0": shape (116, 8), type "<f4">
optimizer_weights/Adam/dense/kernel/v:0 <HDF5 dataset "v:0": shape (116, 8), type "<f4">
optimizer_weights/Adam/dense_1 <HDF5 group "/optimizer_weights/Adam/dense_1" (2 members)>
optimizer_weights/Adam/dense_1/bias <HDF5 group "/optimizer_weights/Adam/dense_1/bias" (2 members)>
optimizer_weights/Adam/dense_1/bias/m:0 <HDF5 dataset "m:0": shape (4,), type "<f4">
optimizer_weights/Adam/dense_1/bias/v:0 <HDF5 dataset "v:0": shape (4,), type "<f4">
optimizer_weights/Adam/dense_1/kernel <HDF5 group "/optimizer_weights/Adam/dense_1/kernel" (2 members)>
optimizer_weights/Adam/dense_1/kernel/m:0 <HDF5 dataset "m:0": shape (8, 4), type "<f4">
optimizer_weights/Adam/dense_1/kernel/v:0 <HDF5 dataset "v:0": shape (8, 4), type "<f4">
optimizer_weights/Adam/dense_2 <HDF5 group "/optimizer_weights/Adam/dense_2" (2 members)>
optimizer_weights/Adam/dense_2/bias <HDF5 group "/optimizer_weights/Adam/dense_2/bias" (2 members)>
optimizer_weights/Adam/dense_2/bias/m:0 <HDF5 dataset "m:0": shape (1,), type "<f4">
optimizer_weights/Adam/dense_2/bias/v:0 <HDF5 dataset "v:0": shape (1,), type "<f4">
optimizer_weights/Adam/dense_2/kernel <HDF5 group "/optimizer_weights/Adam/dense_2/kernel" (2 members)>
optimizer_weights/Adam/dense_2/kernel/m:0 <HDF5 dataset "m:0": shape (4, 1), type "<f4">
optimizer_weights/Adam/dense_2/kernel/v:0 <HDF5 dataset "v:0": shape (4, 1), type "<f4">
optimizer_weights/Adam/iter:0 <HDF5 dataset "iter:0": shape (), type "<i8">

In [49]:
# 2) Load a specific model  `h5py` to run on the data:

from tensorflow.keras.models import load_model
        
better_model = load_model("Resources/AlphabetSoup.h5")
better_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 936

 dense_1 (Dense)             (None, 4)                 36

 dense_2 (Dense)             (None, 1)                 5

=================================================================
Total params: 977
Trainable params: 977
Non-trainable params: 0
_________________________________________________________________